dotenv: .env

wallet:
  key: ${PRIVATE_KEY}

dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.7.0"
  - "smartcontractkit/chainlink@1.6.0"

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.0"
      - "@chainlink=smartcontractkit/chainlink@1.6.0"

networks:
  development:
    verify: False
    
  rinkeby:
    eth_usd_price_feed: "	0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    dai_usd_price_feed: "0x2bA49Aaa16E6afD2a993473cfB70Fa8559B523cF"
    weth_token: "0xc778417E063141139Fce010982780140Aa0cD5Ab"
    fau_token: "0xFab46E002BbF0b4509813474841E0716E6730136"
    verify: True
  
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    dai_usd_price_feed: "0xAed0c38402a5d19df6E4c03F4E2DceD6e29c1ee9"
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    fau_token: "0xFab46E002BbF0b4509813474841E0716E6730136"
    verify: False

  