dotenv: .env

wallet:
  key: ${PRIVATE_KEY}

dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.7.0"

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.0"
